name: pages

on:
  push:
    branches:
      - pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: NPM
        run: npm ci

      - name: Build
        run: node make.mjs build:pages

      - name: Artifact build
        uses: actions/upload-artifact@v3
        with:
          name: pages-build
          path: build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/pages
